[tool.poetry]
name = "part_x"
version = "0.0.1"
description = "PartX - A family of stochastic optimzeres"
authors = ["Aniruddh Vinay Chandratre <achand75@asu.edu>"]

[tool.poetry.dependencies]
python = "^3.7"
treelib = "^1.6.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
